### ISSUE TITLE
Compatibility with WebPack 5

### ISSUE THREAD

**Issue by pearnaly** [abhijithvijayan/wext-manifest-webpack-plugin#2]
Hi @abhijithvijayan,
The plugin seems to not be compatible with Webpack 5. I get following deprecation issues and errors:
```
\ Generating browser application bundles (phase: building)...wext-manifest-webpack-plugin: removed manifest.js
(node:2364) [DEP_WEBPACK_CHUNK_HAS_ENTRY_MODULE] DeprecationWarning: Chunk.hasEntryModule: Use new ChunkGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:2364) [DEP_WEBPACK_CHUNK_ENTRY_MODULE] DeprecationWarning: Chunk.entryModule: Use new ChunkGraph API
(node:2364) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: chunk.files was changed from Array to Set (using Array method 'filter' is deprecated)
√ Browser application bundle generation complete.
An unhandled exception occurred: Cannot read property 'endsWith' of undefined
See "C:\Users\pearn\AppData\Local\Temp\ng-t55ITd\angular-errors.log" for further details.
```

Thank you!
Paul

**Comment by abhijithvijayan** [comment]
Yeah webpack 5 broke a lot of loaders and plugins.

Will be working on supporting for webpack 5

**Comment by willneill** [comment]
Hi @abhijithvijayan, 

Any update on this? Thanks!

**Comment by abhijithvijayan** [comment]
now being worked on.

will be releasing `2.0.0` with this

**Comment by princesust** [comment]
Any update?

**Comment by leozera14** [comment]
Hey @pearnaly, I was searching about this warnings deprecations to fix and remove it from my build and I saw a fix that was made for another package but for the same reason, to fix the warnings about the new ChunkAPI for Webpack v5. With that I read the code and bring to wext-manifest-webpack-plugin. I will let the file with the 
code here and the only thing that u have to do is make a patch and use it in your project. Hope that help all that's getting this warnings.

->Get the code inside the txt and create a file like: node_modules/wext-manifest-webpack-plugin/lib/plugin.js ( make a patch of this using patch-package module )
[plugin_fixed.txt](https://github.com/abhijithvijayan/wext-manifest-webpack-plugin/files/11444505/plugin_fixed.txt)

**Comment by abhijithvijayan-kubric** [comment]
will look into the snippet you shared and try to integrate into the plugin. thanks @leozera14

**Comment by abhijithvijayan** [comment]
webpack 5 support is finally added! Backward compatible with webpack 4 too.
```
wext-manifest-webpack-plugin@^1.4.0
```

thanks @leozera14 for the reference script. It was incompatible with webpack 4 which I have resolved.
